[2024-08-19 22:55:29,694 - INFO - dataIngestion -  >>>> stage Data Ingestion Stage <<<< started !]
[2024-08-19 22:55:29,695 - ERROR - dataIngestion - [Errno 2] No such file or directory: 'data/sleep-dataset.csv']
Traceback (most recent call last):
  File "/home/aman123lug/Desktop/credit-decisioning/src/dataIngestion.py", line 20, in <module>
    data = obj.data_ingestion()
  File "/home/aman123lug/Desktop/credit-decisioning/src/dataIngestion.py", line 11, in data_ingestion
    df = pd.read_csv("data/sleep-dataset.csv")
  File "/home/aman123lug/.local/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 1026, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/aman123lug/.local/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 620, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/aman123lug/.local/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 1620, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/home/aman123lug/.local/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 1880, in _make_engine
    self.handles = get_handle(
  File "/home/aman123lug/.local/lib/python3.10/site-packages/pandas/io/common.py", line 873, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: 'data/sleep-dataset.csv'
